symbols:
  - "LTCBTC"
  - "BTCUSDT"
  - "EOSUSDT"
# max_workers - ограничивает количество параллельно запущенных воркеров, которые делают запросы на биржу
max_workers: 2
binance_url: https://www.binance.com